### ISSUE TITLE
Typo in page 10

### ISSUE THREAD

**Issue by blocodenotas** [twoscoops/two-scoops-of-django-1.8#100] opened 2015-06-13 10:59 UTC
Where it is written: Dashes in actual URLs are fine (e.g. regex='aˆdd-topping/$').
It should real ... regex = '^add_topping/$'

It is actually in page 10...

**Comment by bakasaru** [comment] 2015-07-30 02:13
Duplicate of #86

**Closed as completed** 2016-12-07 05:01 UTC
Labels: duplicate, errata
